### ISSUE TITLE
Doesn't work! 

### ISSUE THREAD

**Issue by m-anish** [bendemott/captiveportal#2]
Get this error log

```
root@box:/opt/iiab/captiveportal# sudo captiveportal start --interface br0 -n --log 
2018-06-28 17:12:44+0000 [-] Log opened.
2018-06-28 17:12:44+0000 [-] set(['http://yui.yahooapis.com/pure/0.5.0/base-min.css', 'http://fonts.googleapis.com/css?family=Raleway:200', 'http://yui.yahooapis.com/pure/0.5.0/pure-min.css', '$referrer_url'])
2018-06-28 17:12:44+0000 [-] captiveportal [13028] started
2018-06-28 17:12:44+0000 [-] Warning: primary log target selected twice at </usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/application/app.py:213> - previously selected at </usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/python/log.py:214>.  Remove one of the calls to beginLoggingTo.
2018-06-28 17:12:44+0000 [-] twistd 18.4.0 (/usr/bin/python 2.7.12) starting up.
2018-06-28 17:12:44+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2018-06-28 17:12:44+0000 [-] Traceback (most recent call last):
2018-06-28 17:12:44+0000 [-]   File "/usr/local/bin/captiveportal", line 4, in <module>
2018-06-28 17:12:44+0000 [-]     __import__('pkg_resources').run_script('captiveportal==0.4', 'captiveportal')
2018-06-28 17:12:44+0000 [-]   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
2018-06-28 17:12:44+0000 [-]     self.require(requires)[0].run_script(script_name, ns)
2018-06-28 17:12:44+0000 [-]   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
2018-06-28 17:12:44+0000 [-]     exec(script_code, namespace, namespace)
2018-06-28 17:12:44+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/captiveportal-0.4-py2.7.egg/EGG-INFO/scripts/captiveportal", line 664, in <module>
2018-06-28 17:12:44+0000 [-]     
2018-06-28 17:12:44+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/captiveportal-0.4-py2.7.egg/EGG-INFO/scripts/captiveportal", line 658, in main
2018-06-28 17:12:44+0000 [-]     
2018-06-28 17:12:44+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/captiveportal-0.4-py2.7.egg/EGG-INFO/scripts/captiveportal", line 543, in start
2018-06-28 17:12:44+0000 [-]     
2018-06-28 17:12:44+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/captiveportal-0.4-py2.7.egg/EGG-INFO/scripts/captiveportal", line 454, in run
2018-06-28 17:12:44+0000 [-]     
2018-06-28 17:12:44+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/scripts/_twistd_unix.py", line 254, in postApplication
2018-06-28 17:12:44+0000 [-]     self.startApplication(self.application)
2018-06-28 17:12:44+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/scripts/_twistd_unix.py", line 442, in startApplication
2018-06-28 17:12:44+0000 [-]     service.IService(application).privilegedStartService()
2018-06-28 17:12:44+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/application/service.py", line 283, in privilegedStartService
2018-06-28 17:12:44+0000 [-]     service.privilegedStartService()
2018-06-28 17:12:44+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/application/service.py", line 283, in privilegedStartService
2018-06-28 17:12:44+0000 [-]     service.privilegedStartService()
2018-06-28 17:12:44+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/application/internet.py", line 114, in privilegedStartService
2018-06-28 17:12:44+0000 [-]     self._port = self._getPort()
2018-06-28 17:12:44+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/application/internet.py", line 142, in _getPort
2018-06-28 17:12:44+0000 [-]     'listen%s' % (self.method,))(*self.args, **self.kwargs)
2018-06-28 17:12:44+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 495, in listenTCP
2018-06-28 17:12:44+0000 [-]     p.startListening()
2018-06-28 17:12:44+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 981, in startListening
2018-06-28 17:12:44+0000 [-]     skt.listen(self.backlog)
2018-06-28 17:12:44+0000 [-]   File "/usr/lib/python2.7/socket.py", line 228, in meth
2018-06-28 17:12:44+0000 [-]     return getattr(self._sock,name)(*args)
2018-06-28 17:12:44+0000 [-] socket.error: [Errno 98] Address already in use
root@box:/opt/iiab/captiveportal# sudo captiveportal start --interface wlan0 -n --log 
2018-06-28 17:12:49+0000 [-] Log opened.
2018-06-28 17:12:49+0000 [-] set(['http://yui.yahooapis.com/pure/0.5.0/base-min.css', 'http://fonts.googleapis.com/css?family=Raleway:200', 'http://yui.yahooapis.com/pure/0.5.0/pure-min.css', '$referrer_url'])
2018-06-28 17:12:49+0000 [-] Traceback (most recent call last):
2018-06-28 17:12:49+0000 [-]   File "/usr/local/bin/captiveportal", line 4, in <module>
2018-06-28 17:12:49+0000 [-]     __import__('pkg_resources').run_script('captiveportal==0.4', 'captiveportal')
2018-06-28 17:12:49+0000 [-]   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
2018-06-28 17:12:49+0000 [-]     self.require(requires)[0].run_script(script_name, ns)
2018-06-28 17:12:49+0000 [-]   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
2018-06-28 17:12:49+0000 [-]     exec(script_code, namespace, namespace)
2018-06-28 17:12:49+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/captiveportal-0.4-py2.7.egg/EGG-INFO/scripts/captiveportal", line 664, in <module>
2018-06-28 17:12:49+0000 [-]     
2018-06-28 17:12:49+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/captiveportal-0.4-py2.7.egg/EGG-INFO/scripts/captiveportal", line 658, in main
2018-06-28 17:12:49+0000 [-]     
2018-06-28 17:12:49+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/captiveportal-0.4-py2.7.egg/EGG-INFO/scripts/captiveportal", line 514, in start
2018-06-28 17:12:49+0000 [-]     
2018-06-28 17:12:49+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/captiveportal-0.4-py2.7.egg/EGG-INFO/scripts/captiveportal", line 238, in get_iface_address
2018-06-28 17:12:49+0000 [-]     
2018-06-28 17:12:49+0000 [-] IOError: [Errno 99] Cannot assign requested address
root@box:/opt/iiab/captiveportal# sudo captiveportal start --interface br0 -n --log 
2018-06-28 17:13:13+0000 [-] Log opened.
2018-06-28 17:13:13+0000 [-] set(['http://yui.yahooapis.com/pure/0.5.0/base-min.css', 'http://fonts.googleapis.com/css?family=Raleway:200', 'http://yui.yahooapis.com/pure/0.5.0/pure-min.css', '$referrer_url'])
2018-06-28 17:13:13+0000 [-] captiveportal [13036] started
2018-06-28 17:13:13+0000 [-] Warning: primary log target selected twice at </usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/application/app.py:213> - previously selected at </usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/python/log.py:214>.  Remove one of the calls to beginLoggingTo.
2018-06-28 17:13:13+0000 [-] twistd 18.4.0 (/usr/bin/python 2.7.12) starting up.
2018-06-28 17:13:13+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2018-06-28 17:13:13+0000 [-] Traceback (most recent call last):
2018-06-28 17:13:13+0000 [-]   File "/usr/local/bin/captiveportal", line 4, in <module>
2018-06-28 17:13:13+0000 [-]     __import__('pkg_resources').run_script('captiveportal==0.4', 'captiveportal')
2018-06-28 17:13:13+0000 [-]   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
2018-06-28 17:13:13+0000 [-]     self.require(requires)[0].run_script(script_name, ns)
2018-06-28 17:13:13+0000 [-]   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
2018-06-28 17:13:13+0000 [-]     exec(script_code, namespace, namespace)
2018-06-28 17:13:13+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/captiveportal-0.4-py2.7.egg/EGG-INFO/scripts/captiveportal", line 664, in <module>
2018-06-28 17:13:13+0000 [-]     
2018-06-28 17:13:13+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/captiveportal-0.4-py2.7.egg/EGG-INFO/scripts/captiveportal", line 658, in main
2018-06-28 17:13:13+0000 [-]     
2018-06-28 17:13:13+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/captiveportal-0.4-py2.7.egg/EGG-INFO/scripts/captiveportal", line 543, in start
2018-06-28 17:13:13+0000 [-]     
2018-06-28 17:13:13+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/captiveportal-0.4-py2.7.egg/EGG-INFO/scripts/captiveportal", line 454, in run
2018-06-28 17:13:13+0000 [-]     
2018-06-28 17:13:13+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/scripts/_twistd_unix.py", line 254, in postApplication
2018-06-28 17:13:13+0000 [-]     self.startApplication(self.application)
2018-06-28 17:13:13+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/scripts/_twistd_unix.py", line 442, in startApplication
2018-06-28 17:13:13+0000 [-]     service.IService(application).privilegedStartService()
2018-06-28 17:13:13+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/application/service.py", line 283, in privilegedStartService
2018-06-28 17:13:13+0000 [-]     service.privilegedStartService()
2018-06-28 17:13:13+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/application/service.py", line 283, in privilegedStartService
2018-06-28 17:13:13+0000 [-]     service.privilegedStartService()
2018-06-28 17:13:13+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/application/internet.py", line 114, in privilegedStartService
2018-06-28 17:13:13+0000 [-]     self._port = self._getPort()
2018-06-28 17:13:13+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/application/internet.py", line 142, in _getPort
2018-06-28 17:13:13+0000 [-]     'listen%s' % (self.method,))(*self.args, **self.kwargs)
2018-06-28 17:13:13+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 495, in listenTCP
2018-06-28 17:13:13+0000 [-]     p.startListening()
2018-06-28 17:13:13+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Twisted-18.4.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 981, in startListening
2018-06-28 17:13:13+0000 [-]     skt.listen(self.backlog)
2018-06-28 17:13:13+0000 [-]   File "/usr/lib/python2.7/socket.py", line 228, in meth
2018-06-28 17:13:13+0000 [-]     return getattr(self._sock,name)(*args)
2018-06-28 17:13:13+0000 [-] socket.error: [Errno 98] Address already in use

```

**Comment by m-anish** [comment]
Closing. (No activity)
